dl
format = edgelist1	
n=54	
data:
outside boy 1.0	
myself i 1.0	
was cheese 1.0	
quick brown 1.0	
killed brown 1.0	
was sisters 1.0	
sisters brothers 1.0	
on mouse 1.0	
rat mouse 2.0	
fox beast 1.0	
killed fox 1.0	
i mouse 1.0	
neighbor boy 1.0	
neighbor fox 1.0	
with myself 1.0	
mouse a 1.0	
on cheese 1.0	
passion a 1.0	
i hate 1.0	
with passion 1.0	
myself hate 1.0	
with a 1.0	
the i 1.0	
passion fox 2.0	
outside neighbor 1.0	
house and 1.0	
his brothers 1.0	
house his 1.0	
his and 3.0	
his hobgoblin 1.0	